[package]
name = "ciphra_pay"
version = "0.2.0"
edition = "2024_07"

[dependencies]
starknet = "2.7.0"

[dev-dependencies]
snforge_std_deprecated = "0.53.0"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.starknet]
sierra = true
casm = true

[tool.snforge]
