[package]
name = "ciphra_pay"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.7.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }

[[target.starknet-contract]]
sierra = true
casm = true
modules = ["AtomicSwap", "Escrow", "BridgeConnector", "P2PTransfer"]

[tool.starknet]
sierra = true
casm = true

[tool.snforge]