[package]
name = "ciphra_pay"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.7.0"

# Tell Scarb your contract modules!!!
[[target.starknet-contract]]
sierra = true
casm = true
# list all modules
modules = ["AtomicSwap", "Escrow", "BridgeConnector"]

[tool.starknet]
sierra = true
casm = true

[tool.snforge]
