[package]
name = "ciphra_pay"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.8.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "main" }

[[target.starknet-contract]]

[tool.snforge]